name 'db'
maintainer 'Justin'
maintainer_email 'jlai@health2sync.com'
license 'all_rights'
description 'Installs/Configures My DB Application'
long_description 'Installs/Configures'
version '0.1.0'

depends 'apt'
depends 'postgresql'