# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">=1.6.0"

boxes = [
  {
    :name => "master",
    :eth1 => "192.168.205.10",
    :mem => "512",
    :cpu => "1"
  },
  {
    :name => "worker1",
    :eth1 => "192.168.205.11",
    :mem => "512",
    :cpu => "1"
  },
  {
    :name => "worker2",
    :eth1 => "192.168.205.12",
    :mem => "512",
    :cpu => "1"
  }
]

Vagrant.configure("2") do |config|
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--name", opts[:name], "--memory", opts[:mem]]
          vb.customize ["modifyvm", :id ,"--name", opts[:name], "--cpus", opts[:cpu]]
      end
      config.vm.box = "ubuntu/xenial64"
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:eth1]
    end
  end

  # refer https://www.vagrantup.com/docs/provisioning/shell.html

  config.vm.provision "shell", inline: <<-SHELL
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" >> ~/kubernetes.list
    sudo mv ~/kubernetes.list /etc/apt/sources.list.d
    sudo apt-get update
    # Install docker if you don't have it already.
    sudo apt-get install -y docker.io
    apt-get install -y kubelet kubeadm kubectl kubernetes-cni
  SHELL
end