driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd


- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
      - recipe[apt]

  - name: cacher
    run_list:
      - recipe[test::cacher]

  - name: compile-time
    run_list:
      - recipe[apt::default]
    attributes:
      apt:
        compile_time_update: true

  - name: resources
    run_list:
      - recipe[test::resources]

  - name: unattended-upgrades
    run_list:
      - recipe[test::unattended-upgrades]
    attributes:
      apt:
        unattended_upgrades:
          enable: true
