# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :app do |app_config|
    app_config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--name", "app", "--memory", "512"]
    end
    app_config.vm.box = "ubuntu/precise64"
    app_config.vm.hostname = "app"
    app_config.vm.network "private_network", ip: "33.33.13.10"
  end

  config.vm.define :db do |db_config|
    db_config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--name", "db", "--memory", "512"]
    end
    db_config.vm.box = "ubuntu/precise64"
    db_config.vm.hostname = "db"
    db_config.vm.network "private_network", ip: "33.33.13.11"
  end
end