version: "3"
services:
  web:
    # pull your image
    image: result0924/get-start:part1
    deploy:
      # run 5 instance of that image as service called web, limit each one to use, at most, 10% of the CPU(across all cores), and 50MB of RAM.
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      # immediately restart containers if one fails.
      restart_policy:
        condition: on-failure
    # map port 80 on the host to web's port 80
    ports:
      - "80:80"
    # instruct web's containers to share port 80 via a load-balanced network called webnet.(Internally, the containers themselves will publish to web's port 80 at an ephemeral port)
    networks:
      - webnet
# Define the webnet network with the default settings(which is a load-balanced overlay network)
networks:
  webnet:
