version: '2.1'

services: 
  web:
    build: .
    command: ["python", "app.py"]
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      pgdb:
        condition: service_healthy
    links:
      - pgdb
    
  pgdb:
    image: postgres
    restart: always
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3

  admin:
    image: adminer
    ports:
      - 8088:8080